# Generated by Django 6.0.3 on 2026-06-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=30)),
                ('ingreso_neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('garante_nombre', models.CharField(max_length=100)),
                ('garante_fecha_nacimiento', models.DateField()),
                ('garante_tipo_trabajo', models.CharField(max_length=40)),
                ('garante_ingreso_neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('garante_antiguedad', models.PositiveIntegerField()),
                ('modelo', models.CharField(max_length=50)),
                ('plan', models.CharField(max_length=20)),
                ('precio_vehiculo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('importe_adjudicacion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('importe_retiro', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_cuotas', models.PositiveIntegerField(default=84)),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cuota_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dolar_oficial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
